### ISSUE TITLE
Question about the structure of the data model

### ISSUE THREAD

**Issue by christianbur** [netascode/terraform-meraki-nac-meraki#12]
The following path is specified in the example [defaults.yaml:](https://github.com/netascode/terraform-meraki-nac-meraki/blob/main/defaults/defaults.yaml)

```
defaults:
  meraki:
      domains:
          organizations:
              login_security:
                  enforce_password_expiration: true
```

I would therefore assume the following path:
`defaults.meraki.domains.organizations.login_security.enforce_password_expiration`
`
In the [meraki_organization.tf,](https://github.com/netascode/terraform-meraki-nac-meraki/blob/b245a0ae9b908326f60351b2c9c730a4c1b3ccfa/meraki_organization.tf#L78C1-L78C200) however, “domain” is not included.

`        enforce_password_expiration                         = try(org.login_security.enforce_password_expiration, local.defaults.meraki.organizations.login_security.enforce_password_expiration, null)`

The readme includes the following example

```
meraki:
  organizations:
    - name: MyOrg1
      administrators:
        - name: Admin1
          email: admin@cisco.com
          networks:
            - name: MyNet1
```
However, the for loops for creating a network require “domains” in the path, the default value does not.

```
#  Create a Network
locals {
  networks = flatten([
    for domain in try(local.meraki.domains, []) : [
      for org in try(domain.organizations, []) : [
        for network in try(org.networks, []) : {
          key             = format("%s/%s/%s", domain.name, org.name, network.name)
          organization_id = data.meraki_organization.organization[org.name].id
          name            = try(network.name, local.defaults.meraki.organizations.networks.name)
          notes           = try(network.notes, local.defaults.meraki.organizations.networks.notes, "")
          product_types   = try(network.product_types, local.defaults.meraki.organizations.networks.product_types, ["appliance", "switch", "wireless"])
          tags            = try(network.tags, local.defaults.meraki.organizations.networks.tags)
          time_zone       = try(network.time_zone, local.defaults.meraki.organizations.networks.time_zone, "America/Los_Angeles")
        }
      ]
    ]
  ])
}
```
