### ISSUE TITLE
Comments/suggestions based on previous usage

### ISSUE THREAD

**Issue by christianbur** [netascode/terraform-meraki-nac-meraki#17]
@jon-humphries since you wanted more feedback
Here are a few comments/suggestions based on my experience with the module so far. 

1. file:README.md
    yaml_files = [“organizations_admins.yaml”] -> yaml_files = [“organizations.yaml”] -> otherwise it does not fit the example

2. variables.tf and versions.tf
   So far I use the environment variable MERAKI_API_KEY from the docs: ttps://github.com/CiscoDevNet/terraform-provider-meraki/blob/main/docs/index.md.
   The reason for this is that I don't want to write the key to git. I am therefore currently commenting out the two lines with api_key.
   Maybe you can use the environment variable TF_VAR_api_key, but I haven't tested this yet.
A description of how to use an environment variable would be helpful. 

3. meraki_organization.tf
   In one of the last changes “”resource “meraki_organization” “organization” “” was introduced instead of “data”, so I had to make an import of the organization.

        ```
            import {
              id = “9999999999999”
              to = module.meraki.meraki_organization.organization[“DEV”]
            }
        ```

    For the import to work, I also had to comment out “management_details” and fill it in according to the output in the terraform plan. 
    The values of management_details should also be in the yaml config file. 
    I think this should be included in the instructions.

4. so that I could use the meraki module effectively, I would have to make a few extensions.

        ```
        locals {
          networks_devices = flatten([
        
            for domain in try(local.meraki.domains, []) : [
              for organization in try(domain.organizations, []) : [
                for network in try(organization.networks, []) : [
                  for device in try(network.devices, []) : {
                    key = format("%s", device.serial)
        
                    data = try(device, null)
                  } if try(network.devices, null) != null
                ] if try(organization.networks, null) != null
              ] if try(domain.organizations, null) != null
            ] if try(local.meraki.domains, null) != null
          ])
        }
        resource "meraki_device" "devices" {
          for_each = { for device in local.networks_devices : device.key => device }
        
          serial  = try(each.value.data.serial, null)
          address = try(each.value.data.address, null)   -> Inheritance from the network would be nice
          name    = try(each.value.data.name, null)
          notes   = try(each.value.data.notes, null)   -> Inheritance from the network would be nice
          tags    = try(each.value.data.tags, null)     -> Inheritance from the network would be nice
          lat     = try(each.value.data.lat, null)
          lng     = try(each.value.data.lng, null)
        
          depends_on = [ meraki_network_device_claim.net_device_claim ]
        }
       ```
     ```

    locals {
      device_switch_ports = flatten([

        for domain in try(local.meraki.domains, []) : [
          for organization in try(domain.organizations, []) : [
            for network in try(organization.networks, []) : [
              for device in try(network.devices, []) : [
                for switch_port in try(device.switch_ports, []) : {
                  serial = device.serial  
                  key = format("%s/%s", device.serial, switch_port.port_id)

                  data = try(switch_port, null)
                } if try(device.switch_ports, null) != null
              ] if try(network.devices, null) != null
            ] if try(organization.networks, null) != null
          ] if try(domain.organizations, null) != null
        ] if try(local.meraki.domains, null) != null
      ])
    }
    resource "meraki_switch_port" "net_switch_ports" {
      for_each = { for port in local.device_switch_ports : port.key => port }

      serial                      = try(each.value.serial, null)
      port_id                     = try(each.value.data.port_id , local.defaults.meraki.networks.devices.switch_ports.port_id , null)
      access_policy_type          = try(each.value.data.access_policy_type , local.defaults.meraki.networks.devices.switch_ports.access_policy_type , null)
      allowed_vlans               = try(each.value.data.allowed_vlans, local.defaults.meraki.networks.devices.switch_ports.allowed_vlans , null)
      dai_trusted                 = try(each.value.data.dai_trusted, local.defaults.meraki.networks.devices.switch_ports.dai_trusted, null)
      enabled                     = try(each.value.data.enable, local.defaults.meraki.networks.devices.switch_ports.enabled, null)
      isolation_enabled           = try(each.value.data.isolation_enabled, local.defaults.meraki.networks.devices.switch_ports.isolation_enabled, null)
      link_negotiation            = try(each.value.data.link_negotiation, local.defaults.meraki.networks.devices.switch_ports.link_negotiation, null)
      name                        = try(each.value.data.name, local.defaults.meraki.networks.devices.switch_ports.name, null)
      poe_enabled                 = try(each.value.data.poe_enabled, local.defaults.meraki.networks.devices.switch_ports.poe_enabled, null)
      rstp_enabled                = try(each.value.data.rstp_enabled, local.defaults.meraki.networks.devices.switch_ports.rstp_enabled, null)
      sticky_mac_allow_list_limit = try(each.value.data.sticky_mac_allow_list_limit, local.defaults.meraki.networks.devices.switch_ports.sticky_mac_allow_list_limit, null)
      stp_guard                   = try(each.value.data.stp_guard, local.defaults.meraki.networks.devices.switch_ports.stp_guard, null)
      type                        = try(each.value.data.type, local.defaults.meraki.networks.devices.switch_ports.type, null)
      udld                        = try(each.value.data.udld, local.defaults.meraki.networks.devices.switch_ports.udld, null)
      vlan                        = try(each.value.data.vlan, local.defaults.meraki.networks.devices.switch_ports.vlan, null)
      voice_vlan                  = try(each.value.data.voice_vlan, local.defaults.meraki.networks.devices.switch_ports.voice_vlan, null)
      profile_enabled             = try(each.value.data.profile_enabled, local.defaults.meraki.networks.devices.switch_ports.profile_enabled, null)
      profile_iname               = try(each.value.data.profile_iname, local.defaults.meraki.networks.devices.switch_ports.profile_iname, null)
      profile_id                  = try(each.value.data.profile_id, local.defaults.meraki.networks.devices.switch_ports.profile_id, null) 
      sticky_mac_allow_list       = try(each.value.data.sticky_mac_allow_list, local.defaults.meraki.networks.devices.switch_ports.sticky_mac_allow_list, null)
      tags                        = try(each.value.data.tags, local.defaults.meraki.networks.devices.switch_ports.tags, null)

      depends_on = [ meraki_network_device_claim.net_device_claim ]
    }

    ```
   ```
    #diese resource habe ich noch nicht getestet
    locals {
        device_ap_wireless_radio_settings = flatten([

            for domain in try(local.meraki.domains, []) : [
            for organization in try(domain.organizations, []) : [
                for network in try(organization.networks, []) : [
                for device in try(network.devices, []) : [
                    for radio_setting in try(device.radio_settings, []) : {
                    serial = device.serial  
                    
                    data = try(radio_setting, null)
                    } if try(device.radio_settings, null) != null
                ] if try(network.devices, null) != null
                ] if try(organization.networks, null) != null
            ] if try(domain.organizations, null) != null
            ] if try(local.meraki.domains, null) != null
        ])
    }
    locals {
        rf_profile_name_to_id = {for idx,res in meraki_wireless_rf_profile.net_wireless_rf_profiles : res.name => res.id}
    }
    resource "meraki_wireless_radio_settings" "net_wireless_radio_settings" {
        for_each = { for ap in local.device_ap_wireless_radio_settings : port.key => port }

        serial                             = try(each.value.serial, null)
        five_ghz_settings_channel          = try(each.value.five_ghz_settings_channel, null)
        five_ghz_settings_channel_width    = try(each.value.five_ghz_settings_channel_width, null)
        two_four_ghz_settings_channel      = try(each.value.two_four_ghz_settings_channel , null)
        two_four_ghz_settings_target_power = try(each.value.two_four_ghz_settings_target_power, null)
        rf_profile_id                      = local.rf_profile_name_to_id["${each.value.data.rf_profile_name}"]
    }
   ```

   ```
    locals {
      networks_wireless_ssid_identity_psk = flatten([

        for domain in try(local.meraki.domains, []) : [
          for organization in try(domain.organizations, []) : [
            for network in try(organization.networks, []) : [
              for ipsk in try(network.wireless_ssid_identity_psk, []) : {
                network_id = meraki_network.network["${domain.name}/${organization.name}/${network.name}"].id

                data = try(ipsk, null)
              } if try(network.wireless_ssid_identity_psk, null) != null
            ] if try(organization.networks, null) != null
          ] if try(domain.organizations, null) != null
        ] if try(local.meraki.domains, null) != null
      ])
    }
    locals {
      gp_name_and_networkid_to_id = {for idx,res in meraki_network_group_policy.net_group_policies : "${res.name}/${res.network_id}" => res.id}
    }
    resource "meraki_wireless_ssid_identity_psk" "net_wireless_ssid_identity_psk" {
      for_each   = { for i, v in local.networks_wireless_ssid_identity_psk : i => v }
      network_id = each.value.network_id
      group_policy_id = local.gp_name_and_networkid_to_id["${each.value.data.group_policy_name}/${each.value.network_id}"]

      number          = try(each.value.data.number, null)
      expires_at      = try(each.value.data.expires_at, null)
      name            = try(each.value.data.name, null)
      passphrase      = try(each.value.data.passphrase, null)

      depends_on = [ meraki_network_group_policy.net_group_policies ]
    }
   ```
    
    The only special feature here is that I have not used a counter but the serial of the device (device.key => device). 
    I thought this would make importing easier and you can create ports according to the “serial/port” scheme (eg. Q3LV-XXXX-XXXX/1), which is more meaningful when there are several thousand ports. 

      At the moment I am still missing a way to assign rf_profile to the accesspoints. I have already written a resouce but have not yet tested it. It would be nice to simply assign this resouce to all accesspoints of a network (networks.devices.wireless). 

    For meraki_wireless_ssid_identity_psk and meraki_wireless_radio_settings, you must specify an rf_profile_id and group_policy_id respectively. I don't think it makes sense to work with these ids in the yaml file, how should a user know this?
    I have therefore introduced the auxiliary variables group_policy_name and rf_profile_name.

5. I am currently using pyyaml to create a config file because i want to avoid repetition. 
   Pyyaml is outside the focus of this project but the following would be very helpful.

  - address, notes, tags:
       the address of the network should be inherited by all devices.
       For this you should add the auxiliary variable “address” under networks. If no “address” has been specified in the devices, the address of the network should be adopted.
       eg. try(device.address, network.address, default.address, null).
       I currently also use this inheritance for the “notes” and “tags”.

  - wireless
      I think most networks are always built according to the same principle. so I always need e.g. three ssids, ipsk, rf_profiles and group_policies. 
      It would be nice to have a way to set these as default values, but with the current defaults you can only set one value as default at a time

  - devices_claim
      I currently manage the serial numbers of the devices under “devices”. I then use a python script to create the devices_claim.serials entries.
      Perhaps you could modify the devices_claim so that you only have to maintain the serials once under “devices”. 

  - path for the devices
      At the moment, all devices are simply listed under “devices:”. It would be nicer to have devices.switch, devices.wireless and devices.appliances. 
      This would make it very easy to assign certain defaults to a specific type. I think this would also make the yaml file clearer. However, I have not yet implemented this. 
    

Attached is a section of my current config file. I have included the defaults here, because the defaults.yaml did not work for me (due to the error with “domain”).
The !inc_file is replaced by pyyaml generators when loading the yaml file with the content of the file. A python script then copies the defaults into the networks and thus creates the yaml file. I also built something like this for !inc_switchport_profile (but it doesn't work at the moment because I use org port profiles). 
The yaml file is then checked, so far I lacked a way to check the yaml file generated by letascode, but this is probably now possible “variable ‘write_merged_yaml_file’ {”, this was also a reason for not using defaults.yaml until now. 

```
---
meraki:
  domains:
    - name: EMEA
      organizations:
        - name: TEST
          defaults:
            networks:
              devices:
                notes: __inherit_from_network__
                address: __inherit_from_network__
                tags: __inherit_from_network__
              time_zone: "Europe/Berlin"
              product_types: ["appliance", "switch", "wireless"]
              group_policies:
                - !inc_file ./config/include.d/group_policies/group_policy_ipsk_wifi_test-a.yml
                - !inc_file ./config/include.d/group_policies/group_policy_ipsk_wifi_test-b.yml
                - !inc_file ./config/include.d/group_policies/group_policy_ipsk_wifi_gast-a.yml
                - !inc_file ./config/include.d/group_policies/group_policy_ipsk_wifi_gast-b.yml       
              wireless_ssids: 
                - !inc_file ./config/include.d/wireless/wireless_ssid_internet_test.yml
                - !inc_file ./config/include.d/wireless/wireless_ssid_internet_gast.yml
                - !inc_file ./config/include.d/wireless/wireless_ssid_intern_test.yml
              wireless_rf_profiles:
                - !inc_file ./config/include.d/wireless/wireless_rf_profile_test_default.yml
              wireless_ssid_identity_psk:
                - !inc_file ./config/include.d/wireless/wireless_ipsk_wifi_test-a.yml
                - !inc_file ./config/include.d/wireless/wireless_ipsk_wifi_test-b.yml
                - !inc_file ./config/include.d/wireless/wireless_ipsk_wifi_gast-a.yml
                - !inc_file ./config/include.d/wireless/wireless_ipsk_wifi_gast-b.yml
              devices_claim:
                serials: __generated_from_devices_serials__

          networks:
            - name: test-net
              address: "teststr. 77, 99994 Musterstadt"
              notes: "my notes"
              tags: ["test-net","poc-location"]   
              devices:
               # switch
               - name: test-net-sw-01
                 serial: Q3LV-XXXX-XXXX
               - name: test-net-sw-02
                 serial: Q3LV-XXXX-XXXX
               - name: test-net-sw-03
                 serial: Q3LV-XXXX-XXXX
               - name: test-net-sw-04
                 serial: Q3LL-XXXX-XXXX
                 #switch_ports: 
                 #  - !inc_switchport_profile ["switch_ports_1x_profile.yml", "1-7@[SPP-Access] Intern", "8@[SPP-Trunk] AccessPoint", "9-10@[SPP-Trunk] Switch/Meraki-Router"] 
               # wireless
               - name: test-net-ap-01
                 serial: Q3KA-XXXX-XXXX
                 #radio_setting: 
                 #  - !inc_file ./config/include.d/wireless/wireless_radio_settings_default.yaml
               - name: test-net-ap-02
                 serial: Q3KA-XXXX-XXXX         
               - name: test-net-ap-03
                 serial: Q3KA-XXXX-XXXX
               - name: test-net-ap-04
                 serial: Q3KA-XXXX-XXXX
               - name: test-net-ap-05
                 serial: Q3KA-XXXX-XXXX
               # appliance
               - name: test-net-mx-01
                 serial: Q3FA-XXXX-XXXX
```

The comments listed here are just suggestions, perhaps a few things can be implemented. 
I am currently already using the organization port profiles from smartports (https://github.com/CiscoDevNet/terraform-provider-meraki/discussions/20), 
unfortunately these are not yet supported by terraform. 
The smpartport automation is also very interesting, because you could configure all switch ports exactly the same for all networks via terraform.
